image: ruby:2.6

stages:
  - test
  - release

lint:
  image: "registry.gitlab.com/gitlab-org/gitlab-build-images:alpine-helm"
  stage: test
  script:
    - helm lint .

pages:
  stage: release
  script:
    - wget https://storage.googleapis.com/kubernetes-helm/helm-v2.13.0-linux-amd64.tar.gz -O /tmp/helm.tar.gz && tar -zxvf /tmp/helm.tar.gz -C /tmp && mv /tmp/linux-amd64/helm /bin/
    - helm init --client-only
    - mkdir -p ./public
    - "echo \"User-Agent: *\nDisallow: /\" > ./public/robots.txt"
    - helm dependency build
    - helm package . --destination ./public
    - helm repo index --url https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME} ./public
    - mv -f ./public/auto-deploy-rails*.tgz /tmp
    - cp ./public/index.yaml ./chart_site/ && mv -f ./public/index.yaml ./chart_site/_data/
    - "echo \"---\nlayout: home\n---\" > ./chart_site/readme.md && cat ./README.md >> ./chart_site/readme.md"
    - cd chart_site && bundle install
    - jekyll build --destination ../public && rm ../public/feed.xml && cd ..
    - mv /tmp/*.tgz ./public
  artifacts:
    paths:
      - public
  only:
    - master
