# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: IfNotPresent
  secrets:
    - name: gitlab-registry
podAnnotations: {}
podAntiAffinity: true
application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
  secretName:
  secretChecksum:
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
gitlab:
  app:
  env:
  envName:
  envURL:
service:
  replicaCount: 1
  revisionHistoryLimit: 10
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  url: http://my.host.com/
  additionalHosts:
  commonName:
  externalPort: 3000
  internalPort: 3000
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
ingress:
  tls:
    enabled: true
    secretName: ""
  annotations: {}
livenessProbe:
  path: "/"
  initialDelaySeconds: 20
  timeoutSeconds: 15
  scheme: "HTTP"
  periodSeconds: 30
readinessProbe:
  path: "/"
  initialDelaySeconds: 10
  timeoutSeconds: 3
  scheme: "HTTP"
worker:
  enabled: true
  args: 'bundle exec sidekiq'
  replicaCount: 1
  revisionHistoryLimit: 10
  terminationGracePeriodSeconds: 20 # Sidekiq jobs are usually small and fast, 20 is enough
  podAntiAffinity: true
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001
  sidekiq_alive:
    enabled: true
    livenessProbe:
      path: "/"
      initialDelaySeconds: 60 # App specific, tune after deployment
      timeoutSeconds: 15
      port: 7433
      periodSeconds: 30
    readinessProbe:
      path: "/"
      initialDelaySeconds: 30 # App specific, tune after deployment
      timeoutSeconds: 5 # Can be less
      port: 7433
  # SIGTERM triggers a quick exit; gracefully terminate instead
  preStopCommand: ["bundle", "exec", "sidekiqctl", "quiet", "/tmp/sidekiq.pid", "0"]
  resources: {}
  #  limits:
  #    cpu: 100m
  #    memory: 128Mi
  # requests:
  #    cpu: 100m
  #    memory: 128Mi

postgresql:
  enabled: false
resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
# requests:
#    cpu: 100m
#    memory: 128Mi

## Configure PodDisruptionBudget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
#
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1
