# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
  secrets:
    - name: gitlab-registry
podAnnotations: {}
application:
  track: stable
  tier: web
  migrateCommand:
  initializeCommand:
  secretName:
  secretChecksum:
gitlab:
  app:
  env:
service:
  replicaCount: 1
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  url: http://my.host.com/
  additionalHosts:
  commonName:
  externalPort: 3000
  internalPort: 3000
ingress:
  tls:
    enabled: true
    secretName: ""
  annotations: {}
livenessProbe:
  path: "/"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
readinessProbe:
  path: "/"
  initialDelaySeconds: 5
  timeoutSeconds: 3
  scheme: "HTTP"
worker:
  enabled: true
  args: 'bundle exec sidekiq'
  replicaCount: 1
  sidekiq_alive:
    enabled: true
    livenessProbe:
      path: "/"
      initialDelaySeconds: 120 # App specific, tune after deployment
      timeoutSeconds: 15
      port: 7433
    readinessProbe:
      path: "/"
      initialDelaySeconds: 120 # App specific, tune after deployment
      timeoutSeconds: 5 # Can be less
      port: 7433

postgresql:
  enabled: false
resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

## Configure PodDisruptionBudget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
#
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1
