{{- if not .Values.application.initializeCommand -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}-worker
  labels:
    app: {{ template "appname" . }}-worker
    part: 'backend-worker'
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  revisionHistoryLimit: {{ .Values.worker.revisionHistoryLimit | default 10 }}
  template:
    metadata:
      annotations:
        checksum/application-secrets: "{{ .Values.application.secretChecksum }}"
      labels:
        app: {{ template "appname" . }}
        part: 'backend-worker'
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
      - name: {{ .Chart.Name }}-worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["{{ .Values.worker.args | default "bundle exec sidekiq" }}"]
        {{- if .Values.worker.sidekiq_alive.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.worker.sidekiq_alive.livenessProbe.path }}
            port: {{ .Values.worker.sidekiq_alive.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.worker.sidekiq_alive.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.worker.sidekiq_alive.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.worker.sidekiq_alive.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.worker.sidekiq_alive.readinessProbe.path }}
            port: {{ .Values.worker.sidekiq_alive.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.worker.sidekiq_alive.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.worker.sidekiq_alive.readinessProbe.timeoutSeconds }}
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["bundle", "exec", "sidekiqctl", "quiet", "/tmp/sidekiq.pid", "0"]
        {{- end }}
        {{- if .Values.application.secretName }}
        envFrom:
        - secretRef:
            name: {{ .Values.application.secretName }}
        {{- end }}
        {{- if .Values.application.database_host }}
        env:
        - name: DATABASE_HOST
          value: {{ .Values.application.database_host | quote }}
        {{- end }}
        {{- if .Values.application.database_url }}
        env:
        - name: DATABASE_URL
          value: {{ .Values.application.database_url | quote }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end -}}
